// The demo tour — four steps that tell a stranger what they are looking at.
//
// WHY THIS EXISTS, AND WHY IT IS DEMO-ONLY. The public demo hands a link to somebody who has never
// seen Bean. What they land on is an inbox of ten emails in three colours, and the colours are the
// entire product: the green pile is the throwaway 80%, and the yellow pile — drafted, but with a
// stated reason Bean is not sure — is the thing worth building. Nobody reads that off a list of
// coloured rows in the ten seconds they will give it. Before this, the demo relied on whoever sent
// the link narrating it in person, which is exactly the demo you cannot send.
//
// It is gated on `window.BEAN_DEMO_TENANT` (bean/server.py:_serve_data_jsx), for the same reason the
// onboarding overlay is skipped there and the reverse: the operator does not need to be told what
// her own inbox is, and a coach-mark walking her through her morning would be an interruption, not
// a feature. Off unless a deployment explicitly sets the flag.
//
// It writes nothing and fetches nothing. `localStorage` only, so it plays once per visitor and a
// second tab or a refresh does not re-open it — and under BEAN_DEMO_READONLY there is no volume for
// it to have written to anyway.
//
// The steps find their targets by CONFIDENCE (`[data-conf=...]` on `.inbox-row`, bean-inbox.jsx),
// never by email id. The demo fixture is regenerated by running the goldens through the real engine
// (bean/demo.py), so which email lands in which bucket is the engine's call and may move; a tour
// pinned to `sw-fabric` would silently point at the wrong row the first time it did. A step whose
// target is missing is SKIPPED rather than rendered pointing at nothing.

const _T = (typeof React !== 'undefined' && React) || window.React;

const TOUR_KEY = 'bean_tour_seen';

// `target` is a selector resolved when the step opens; null means "no target, just talk". Copy is
// Bean's own voice, light — the same register as the greeting ("Me sorted them, surest first"),
// not the heavier Bean-speak of the questionnaire.
const TOUR_STEPS = [
  {
    key: 'intro',
    target: null,
    title: 'Me read your mail while you slept.',
    body: 'Ten emails came in. Me sorted them by how sure me is about the answer, and me wrote a '
        + 'draft for the ones me could. Nothing was sent. Me never sends — that part is always you.',
  },
  {
    key: 'low',
    target: '.inbox-row[data-conf="low"]',
    title: 'This one is the whole point.',
    body: 'Me drafted a reply, and me told you why me is not sure about it. Read the grey line: '
        + 'that is me saying what me could not find. A robot that sounds confident every time is '
        + 'one you have to re-read every time, and then me saved you nothing.',
  },
  {
    key: 'flag',
    target: '.inbox-row[data-conf="flag"]',
    title: 'And here me does not try.',
    body: 'Some mail has no answer me can reach — a refund to approve, a cancellation somebody has '
        + 'to go and do. Me gathers what you need and hands it over. Me would rather say "this one '
        + 'is yours" than make something up.',
  },
  {
    key: 'high',
    target: '.inbox-row[data-conf="high"]',
    title: 'Green means me can show its work.',
    body: 'Me only calls a draft ready when me can point at the notebook line or the past reply it '
        + 'came from. Open it and the citations are right there to click.',
  },
  {
    key: 'outro',
    target: null,
    title: 'Have a click around.',
    body: 'Open any email to read the draft, edit it, or send it back to me. Nothing here is saved '
        + 'and nothing here is real mail — this store is invented, and the demo forgets you the '
        + 'moment you close the tab. If you want me on your own inbox, the link is up in the '
        + 'greeting.',
  },
];

// The class parked on whichever element the current step is about. Defined in Bean.html next to the
// tour's own styles; it lifts the row and rings it, and does nothing else — no clip-path cutout
// over the page, because a real overlay would steal the click that the last step is asking for.
const SPOT_CLASS = 'bean-tour-spot';

function clearSpot() {
  const prev = document.querySelectorAll('.' + SPOT_CLASS);
  for (let i = 0; i < prev.length; i++) prev[i].classList.remove(SPOT_CLASS);
}

function BeanTour({ onDone }) {
  // Resolve the steps against the DOM ONCE, and drop the ones whose target is not there.
  //
  // ⚠️ IN AN EFFECT, NOT A useMemo, AND THE DIFFERENCE IS THE WHOLE FEATURE. This component mounts
  // in the same commit as the inbox rows it points at, and a useMemo runs during render — before
  // React has put anything in the document. Every querySelector would miss, all three targeted
  // steps would be filtered out, and the tour would degrade to its two untargeted steps without
  // erroring anywhere. An effect runs after the commit, when the rows exist.
  //
  // Resolved once and held in state rather than recomputed per render, because `Clear` deletes rows:
  // a tour that renumbers itself from "2 of 5" to "2 of 4" mid-walk reads as a bug.
  const [steps, setSteps] = _T.useState(null);
  _T.useEffect(() => {
    setSteps(TOUR_STEPS.filter(s => !s.target || document.querySelector(s.target)));
  }, []);
  const [i, setI] = _T.useState(0);
  const step = steps && steps[i];

  _T.useEffect(() => {
    clearSpot();
    if (!step || !step.target) return;
    const el = document.querySelector(step.target);
    if (!el) return;   // vanished since mount (a Clear on that very row) — talk, don't point
    el.classList.add(SPOT_CLASS);
    // `block: 'center'` and not 'nearest': the tour bar is pinned to the bottom of the viewport, and
    // 'nearest' happily parks the row underneath it. Smooth scrolling is motion, so it answers to
    // prefers-reduced-motion the same as the keyframes in Bean.html do — asked here rather than in
    // the stylesheet because this is the one piece of movement the CSS cannot reach.
    let smooth = true;
    try { smooth = !window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}
    try { el.scrollIntoView({ behavior: smooth ? 'smooth' : 'auto', block: 'center' }); }
    catch (e) { el.scrollIntoView(); }
    return () => { el.classList.remove(SPOT_CLASS); };
  }, [step && step.key]);

  // Leaving the tour by ANY route — finishing it, skipping it, unmounting because the visitor
  // navigated to the Notebook — must take the ring with it. Without this the highlight outlives the
  // thing that explained it, which looks like a stuck selection.
  _T.useEffect(() => clearSpot, []);

  function finish() {
    clearSpot();
    // Private browsing or storage disabled: the only cost is the tour saying hello again on the next
    // load, which for a demo is a mild annoyance and not worth a second mechanism.
    try { localStorage.setItem(TOUR_KEY, '1'); } catch (e) {}
    onDone();
  }

  if (!step) return null;   // still resolving, or nothing left to say
  const last = i === steps.length - 1;

  return _T.createElement('div', { className: 'bean-tour', role: 'dialog', 'aria-label': 'A quick tour of Bean' },
    _T.createElement('div', { className: 'bean-tour-mark' },
      window.PlayfulMark ? _T.createElement(window.PlayfulMark, { size: 34 }) : null),
    _T.createElement('div', { className: 'bean-tour-body' },
      _T.createElement('div', { className: 'bean-tour-count' }, (i + 1) + ' of ' + steps.length),
      _T.createElement('h3', null, step.title),
      _T.createElement('p', null, step.body)
    ),
    _T.createElement('div', { className: 'bean-tour-acts' },
      i > 0 && _T.createElement('button', {
        type: 'button', className: 'bean-tour-back', onClick: () => setI(n => n - 1),
      }, 'Back'),
      _T.createElement('button', {
        type: 'button', className: 'bean-tour-next',
        onClick: () => (last ? finish() : setI(n => n + 1)),
      }, last ? 'Let me look' : 'Next')
    ),
    _T.createElement('button', {
      type: 'button', className: 'bean-tour-x', onClick: finish, 'aria-label': 'Skip the tour',
    }, '×')
  );
}

// Has this visitor already been walked through it? Read at mount in bean-root, not here, so the
// answer is settled once per page load rather than re-read on every render.
function tourSeen() {
  // A throw means storage is unavailable, and the honest answer there is "yes, seen" — a tour that
  // reopens on every single load in a locked-down browser is worse than one nobody ever gets.
  try { return !!localStorage.getItem(TOUR_KEY); } catch (e) { return true; }
}

window.BeanTour = BeanTour;
window.beanTourSeen = tourSeen;
